package models

import (

	"errors"
	"gorm.io/driver/postgres"
	_ "gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

var (
	// ErrNotFound is returned when a resource cannot
	// be found in the database.
	ErrNotFound = errors.New("models: resource not found")

	ErrInvalidID = errors.New("models: ID must be > 0")
)

func NewUserService(connectionInfo string) (*UserService, error) {
	db, err := gorm.Open(postgres.Open(connectionInfo), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Info),
	})
	if err != nil {
		return nil, err
	}
	return &UserService{
		db: db,
	}, nil
}
// Update will update the provided user with all of the data
// in the provided user object
func (us *UserService) Update(user *User) error {
	return us.db.Save(user).Error
}
// DestructiveReset drops a table and rebuilds it
func (us *UserService) DestructiveReset() {
	_ = us.db.Migrator().DropTable(&User{})
	_ = us.db.AutoMigrate(&User{})
}

// Create will create the provided user and backfill
// data like the ID, CreatedAt, and UpdatedAt fields
func (us *UserService) Create(user *User) error {
	return us.db.Create(user).Error
}
// Delete will delete the user with the provided ID
func (us *UserService) Delete(id uint) error {
	if id == 0 {
		return ErrInvalidID
	}
	user := User{Model: gorm.Model{ID: id}}
	return us.db.Delete(&user).Error
}

type UserService struct {
	db *gorm.DB
}

// ByID will look up a user with the provided ID.
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong.  This may not be an error generated by the models package.
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (us *UserService) ByID(id uint) (*User, error) {
	var user User
	db := us.db.Where("id = ?", id)
	err := first(db, &user)
	return &user, err
}

// ByEmail looks up a user with the given email address and returns that user
// If the user is found, we will return a nil error
// If the user is not found, we will return ErrNotFound
// If there is another error, we will return an error with
// more information about what went wrong.  This may not be an error generated by the models package.
//
// As a general rule, any error but ErrNotFound should
// probably result in a 500 error.
func (us *UserService) ByEmail(email string) (*User, error) {
	var user User
	db := us.db.Where("email = ?", email)
	err := first(db, &user)
	return &user, err

}
// first will query using the provided gorm.DB and it will get the first
// item returned and place it into dst.  If nothing is
// found in the query, it will return ErrNotFound
func first(db *gorm.DB, dst interface{}) error {
	err := db.First(dst).Error
		if err == gorm.ErrRecordNotFound {
		return ErrNotFound
	}
	return err
}

type User struct {
	gorm.Model
	Name string
	Email string `gorm:"not null;unique_index"`
}